### ISSUE TITLE
range error while reading in csv

### ISSUE THREAD

**Issue by b-meson** [pierwill/unsettling-narratives#1]
```
    def narrative():
     with open('static/test.csv','r') as f:
            csvreader = csv.reader(f)
            narr_id = random.randrange(1,71)
            case = list(csv.reader(f))[narr_id]
            dataset = case[0]
            source = case[1]
            link = case[2]
            neighborhood = case[3]
            date = case[7]
    IndexError: list index out of range
```

Error seems to be caused by `File "unsettling-narratives/serve.py"`, line 40, in `narrative`

**Comment by pierwill** [comment]
Ya I'm not sure what's causing this.

**Comment by pierwill** [comment]
Code is nonsense here:

https://github.com/pierwill/unsettling-narratives/blob/fd751288dfa80e0c7a36ad2ae382735948a44ee0/serve.py#L32-L34

```csvreader``` isn't even used. And running `case = list(csv.reader(f))[narr_id]` in the interpreter throws all kinds a errors.
